# Generated by Django 4.0.3 on 2022-03-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_country_city_alter_userprofile_city_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
