# Generated by Django 4.0.3 on 2022-03-13 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('speciality', models.CharField(blank=True, choices=[('Dermatologists', 'Dermatologists'), ('Cardiologists', 'Cardiologists'), ('Gastroenterologist', 'Gastroenterologist'), ('Physiotherapist', 'Physiotherapist'), ('Pharmacist', 'Pharmacist'), ('Orthopaedist', 'Orthopaedist'), ('Nephrologist', 'Nephrologist'), ('Neurologist', 'Neurologist'), ('Rectal Surgeons', 'Rectal Surgeons'), ('Anesthesiologists', 'Anesthesiologists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists')], max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, choices=[('Anesthesiology', 'Anesthesiology'), ('Pharmacy', 'Pharmacy'), ('Radiology', 'Radiology'), ('Gastroenterology', 'Gastroenterology'), ('Orthopaedics', 'Orthopaedics'), ('Community Medicine', 'Community Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Laboratory', 'Laboratory'), ('Nursing', 'Nursing'), ('Medical Records', 'Medical Records'), ('Cardiology', 'Cardiology'), ('Pediatrics', 'Pediatrics'), ('Obstetics', 'Obstetics'), ('Nephrology', 'Nephrology'), ('Physiotherapy', 'Physiotherapy')], max_length=50, null=True)),
                ('med_reps', models.FileField(blank=True, upload_to='profile/med_reps')),
                ('case_paper', models.IntegerField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, help_text='Write something about yourself, not more than 300 words', max_length=300, null=True)),
                ('education', models.CharField(blank=True, help_text='Eductional Background', max_length=100)),
                ('training', models.CharField(blank=True, help_text='Training Attended', max_length=100)),
                ('certificate', models.CharField(blank=True, help_text='Cerficate and award', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, default='/avatar.png', null=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('linkedIn', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
